// Writes the precache list and a content-hash version into public/sw.js.
// Any change to any precached file changes the version, so browsers always install a fresh,
// consistent copy of the app. Run: node scripts/stamp-sw.mjs  (the unit tests fail if stale).
import { readdir, readFile, writeFile, stat } from 'node:fs/promises';
import { createHash } from 'node:crypto';
import { join, relative, sep } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = fileURLToPath(new URL('../public/', import.meta.url));
const SW = join(ROOT, 'sw.js');
const EXCLUDE = [/^sw\.js$/, /^_headers$/, /^_redirects$/, /^assets\/splash\//, /^assets\/screenshots\//, /\.map$/, /(^|\/)\./, /^robots\.txt$/];

async function walk(dir) {
  const out = [];
  for (const entry of await readdir(dir, { withFileTypes: true })) {
    const full = join(dir, entry.name);
    if (entry.isDirectory()) out.push(...(await walk(full)));
    else out.push(full);
  }
  return out;
}

export async function computeManifest() {
  const files = (await walk(ROOT))
    .map((f) => relative(ROOT, f).split(sep).join('/'))
    .filter((f) => !EXCLUDE.some((re) => re.test(f)))
    .sort();
  const hash = createHash('sha256');
  for (const f of files) {
    hash.update(f);
    hash.update(await readFile(join(ROOT, f)));
  }
  return { version: hash.digest('hex').slice(0, 16), urls: files.map((f) => `/${f}`) };
}

export function renderRegion({ version, urls }) {
  return `// <precache-manifest> (generated by scripts/stamp-sw.mjs — do not edit by hand)
const VERSION = '${version}';
const PRECACHE = ${JSON.stringify(urls, null, 2).replace(/"/g, "'")};
// </precache-manifest>`;
}

/**
 * Static import closure of an entry module (dynamic imports are left lazy on purpose).
 * @param {string} entry path under public/, e.g. "js/main.js"
 */
export async function staticImports(entry) {
  const seen = new Set();
  const visit = async (/** @type {string} */ rel) => {
    if (seen.has(rel)) return;
    seen.add(rel);
    const src = await readFile(join(ROOT, rel), 'utf8');
    for (const m of src.matchAll(/^\s*(?:import|export)\s[^'"`;]*?from\s*['"](\.{1,2}\/[^'"]+)['"]/gm)) {
      const target = relative(ROOT, join(ROOT, rel, '..', m[1])).split(sep).join('/');
      await visit(target);
    }
  };
  await visit(entry);
  seen.delete(entry);
  return [...seen].sort().map((f) => `/${f}`);
}

/** @param {string[]} urls */
export function renderPreloads(urls) {
  return `<!-- <modulepreload> -->\n${urls.map((u) => `    <link rel="modulepreload" href="${u}" />`).join('\n')}\n    <!-- </modulepreload> -->`;
}

/** Injects <link rel="modulepreload"> for the entry's static module graph into an HTML page. */
async function stampPreloads(/** @type {string} */ page, /** @type {string} */ entry) {
  const file = join(ROOT, page);
  const html = await readFile(file, 'utf8');
  const re = /<!-- <modulepreload> -->[\s\S]*?<!-- <\/modulepreload> -->/;
  if (!re.test(html)) throw new Error(`modulepreload markers not found in ${page}`);
  const next = html.replace(re, renderPreloads(await staticImports(entry)));
  if (next !== html) await writeFile(file, next);
}

export async function stamp() {
  await stampPreloads('index.html', 'js/main.js');
  await stampPreloads('share.html', 'js/share/view.js');
  const manifest = await computeManifest();
  const source = await readFile(SW, 'utf8');
  const re = /\/\/ <precache-manifest>[\s\S]*?\/\/ <\/precache-manifest>/;
  if (!re.test(source)) throw new Error('precache markers not found in sw.js');
  const next = source.replace(re, renderRegion(manifest));
  if (next !== source) await writeFile(SW, next);
  return manifest;
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  await stat(SW);
  const m = await stamp();
  console.log(`sw.js stamped: version ${m.version}, ${m.urls.length} files`);
}
